	<link rel="stylesheet" href="{{ asset('plugins/css/bootstrap-style-10.css') }}">
	<link rel="stylesheet" href="{{ asset('plugins/css/animate.css') }}">
	<link rel="stylesheet" href="{{ asset('plugins/css/sweetalert.css') }}">
	<link rel="stylesheet" href="{{ asset('plugins/chosen/chosen.css') }}">
	<link rel="stylesheet" href="{{ asset('plugins/css/jquery-confirm.css') }}">
	<link rel="stylesheet" href="{{ asset('plugins/css/simple-sidebar.css') }}">
	<link rel="stylesheet" href="{{ asset('plugins/css/fileinput.css') }}">
	<link rel="stylesheet" href="{{ asset('plugins/css/bootstrap-formhelpers.css') }}">
	<link rel="stylesheet" href="{{ asset('plugins/trumbowyg/ui/trumbowyg.css') }}">
	<link rel="stylesheet" href="{{ asset('plugins/css/main.css') }}">
