<?php

/*
|--------------------------------------------------------------------------
| Model Factories
|--------------------------------------------------------------------------
|
| Here you may define all of your model factories. Model factories give
| you a convenient way to create models for testing and seeding your
| database. Just tell the factory how a default model should look.
|
*/

$factory->define(App\User::class, function (Faker\Generator $faker) {
    return [
        'name' => $faker->name,
        'email' => $faker->unique()->safeEmail,
        'password' => bcrypt('anderson'),
        'type' => 'member',
        'img_user' => $faker->randomElement($array = array ('user_1.jpg',
                                                            'user_2.jpg',
                                                            'user_3.jpg',
                                                            'user_4.jpg',
                                                            'user_5.jpg',
                                                            'user_6.jpg',
                                                            'user_7.jpg',
                                                            'user_8.jpg',
                                                            'user_9.jpg',
                                                            'user_10.jpg',
                                                            'user_11.jpg',
                                                            'user_12.jpg',
                                                            'user_13.jpg',
                                                            'user_14.jpg',
                                                            'user_15.jpg',
                                                            'user_16.jpg',
                                                            'user_17.jpg',
                                                            'user_18.jpg',
                                                            'user_19.jpg',
                                                            'user_20.jpg')),
        'img_bio' => $faker->randomElement($array = array ('portada.jpg')),
        'sex' => $faker->randomElement($array = array ('Masculino','Femenino')),
        'fecha' => $faker->dateTimeBetween($startDate = '-30 years', $endDate = 'now')
    ];
});

$factory->define(App\Category::class, function (Faker\Generator $faker) {
    return [
        'name' => $faker->unique()->word
    ];
});

$factory->define(App\Tag::class, function (Faker\Generator $faker) {
    return [
        'name' => $faker->unique()->word
    ];
});

$factory->define(App\Article::class, function (Faker\Generator $faker) {
    return [
        'title' => $faker->unique()->sentence($nbWords = 6, $variableNbWords = true),
        'content' => $faker->paragraph($nbSentences = 50, $variableNbSentences = true),
        'user_id' => $faker->biasedNumberBetween($min = 3, $max = 52, $function = 'sqrt'),
        'category_id' => $faker->biasedNumberBetween($min = 1, $max = 50, $function = 'sqrt'),
        'img_dest' => $faker->randomElement($array = array ('001.jpg',
                                                            '002.jpg',
                                                            '003.jpg',
                                                            '004.jpg',
                                                            '005.jpg',
                                                            '006.jpg',
                                                            '007.jpg',
                                                            '008.jpg',
                                                            '009.jpg',
                                                            '010.jpg',
                                                            '011.jpg',
                                                            '012.jpg',
                                                            '013.jpg',
                                                            '014.jpg',
                                                            '015.jpg',
                                                            '016.jpg',
                                                            '017.jpg',
                                                            '018.jpg',
                                                            '019.jpg',
                                                            '020.jpg',
                                                            '021.jpg',
                                                            '022.jpg',
                                                            '023.jpg',
                                                            '024.jpg',
                                                            '025.jpg',
                                                            '026.jpg',
                                                            '027.jpg',
                                                            '028.jpg',
                                                            '029.jpg',
                                                            '030.jpg',
                                                            '031.jpg',
                                                            '032.jpg',
                                                            '033.jpg',
                                                            '034.jpg',
                                                            '035.jpg',
                                                            '036.jpg',
                                                            '037.jpg',
                                                            '038.jpg',
                                                            '039.jpg',
                                                            '040.jpg',
                                                            '041.jpg',
                                                            '042.jpg',
                                                            '043.jpg',
                                                            '044.jpg',
                                                            '045.jpg',
                                                            '046.jpg',
                                                            '047.jpg',
                                                            '048.jpg',
                                                            '049.jpg',
                                                            '050.jpg',
                                                            '051.jpg',
                                                            '052.jpg',
                                                            '053.jpg',
                                                            '054.jpg',
                                                            '055.jpg',
                                                            '056.jpg',
                                                            '057.jpg',
                                                            '058.jpg',
                                                            '059.jpg',
                                                            '060.jpg',
                                                            '061.jpg',
                                                            '062.jpg',
                                                            '063.jpg',
                                                            '064.jpg',
                                                            '065.jpg',
                                                            '066.jpg',
                                                            '067.jpg',
                                                            '068.jpg',
                                                            '069.jpg',
                                                            '070.jpg',
                                                            '071.jpg',
                                                            '072.jpg',
                                                            '073.jpg',
                                                            '074.jpg',
                                                            '075.jpg',
                                                            '076.jpg',
                                                            '077.jpg',
                                                            '078.jpg',
                                                            '079.jpg',
                                                            '080.jpg',
                                                            '071.jpg',
                                                            '072.jpg',
                                                            '073.jpg',
                                                            '074.jpg',
                                                            '075.jpg',
                                                            '076.jpg',
                                                            '077.jpg',
                                                            '078.jpg',
                                                            '079.jpg',
                                                            '080.jpg',
                                                            '081.jpg',
                                                            '082.jpg',
                                                            '083.jpg',
                                                            '084.jpg',
                                                            '085.jpg',
                                                            '086.jpg',
                                                            '087.jpg',
                                                            '088.jpg',
                                                            '089.jpg',
                                                            '090.jpg',
                                                            '091.jpg',
                                                            '092.jpg',
                                                            '093.jpg',
                                                            '094.jpg',
                                                            '095.jpg',
                                                            '096.jpg',
                                                            '097.jpg',
                                                            '098.jpg',
                                                            '099.jpg',
                                                            '100.jpg',
                                                            '101.jpg',
                                                            '102.jpg',
                                                            '103.jpg',
                                                            '104.jpg',
                                                            '105.jpg',
                                                            '106.jpg',
                                                            '107.jpg',
                                                            '108.jpg',
                                                            '109.jpg',
                                                            '110.jpg',
                                                            '111.jpg',
                                                            '112.jpg',
                                                            '113.jpg',
                                                            '114.jpg',
                                                            '115.jpg',
                                                            '116.jpg',
                                                            '117.jpg',
                                                            '118.jpg',
                                                            '119.jpg',
                                                            '120.jpg',
                                                            '121.jpg',
                                                            '122.jpg',
                                                            '123.jpg',
                                                            '124.jpg',
                                                            '125.jpg',
                                                            '126.jpg',
                                                            '127.jpg',
                                                            '128.jpg',
                                                            '129.jpg',
                                                            '130.jpg',
                                                            '131.jpg',
                                                            '132.jpg',
                                                            '133.jpg',
                                                            '134.jpg',
                                                            '135.jpg',
                                                            '136.jpg',
                                                            '137.jpg',
                                                            '138.jpg',
                                                            '139.jpg',
                                                            '140.jpg'))
    ];
});

$factory->define(App\Image::class, function (Faker\Generator $faker) {
    return [
        'name' => $faker->randomElement($array = array ('001.jpg',
                                                        '002.jpg',
                                                        '003.jpg',
                                                        '004.jpg',
                                                        '005.jpg',
                                                        '006.jpg',
                                                        '007.jpg',
                                                        '008.jpg',
                                                        '009.jpg',
                                                        '010.jpg',
                                                        '011.jpg',
                                                        '012.jpg',
                                                        '013.jpg',
                                                        '014.jpg',
                                                        '015.jpg',
                                                        '016.jpg',
                                                        '017.jpg',
                                                        '018.jpg',
                                                        '019.jpg',
                                                        '020.jpg',
                                                        '021.jpg',
                                                        '022.jpg',
                                                        '023.jpg',
                                                        '024.jpg',
                                                        '025.jpg',
                                                        '026.jpg',
                                                        '027.jpg',
                                                        '028.jpg',
                                                        '029.jpg',
                                                        '030.jpg',
                                                        '031.jpg',
                                                        '032.jpg',
                                                        '033.jpg',
                                                        '034.jpg',
                                                        '035.jpg',
                                                        '036.jpg',
                                                        '037.jpg',
                                                        '038.jpg',
                                                        '039.jpg',
                                                        '040.jpg',
                                                        '041.jpg',
                                                        '042.jpg',
                                                        '043.jpg',
                                                        '044.jpg',
                                                        '045.jpg',
                                                        '046.jpg',
                                                        '047.jpg',
                                                        '048.jpg',
                                                        '049.jpg',
                                                        '050.jpg',
                                                        '051.jpg',
                                                        '052.jpg',
                                                        '053.jpg',
                                                        '054.jpg',
                                                        '055.jpg',
                                                        '056.jpg',
                                                        '057.jpg',
                                                        '058.jpg',
                                                        '059.jpg',
                                                        '060.jpg',
                                                        '061.jpg',
                                                        '062.jpg',
                                                        '063.jpg',
                                                        '064.jpg',
                                                        '065.jpg',
                                                        '066.jpg',
                                                        '067.jpg',
                                                        '068.jpg',
                                                        '069.jpg',
                                                        '070.jpg',
                                                        '071.jpg',
                                                        '072.jpg',
                                                        '073.jpg',
                                                        '074.jpg',
                                                        '075.jpg',
                                                        '076.jpg',
                                                        '077.jpg',
                                                        '078.jpg',
                                                        '079.jpg',
                                                        '080.jpg',
                                                        '071.jpg',
                                                        '072.jpg',
                                                        '073.jpg',
                                                        '074.jpg',
                                                        '075.jpg',
                                                        '076.jpg',
                                                        '077.jpg',
                                                        '078.jpg',
                                                        '079.jpg',
                                                        '080.jpg',
                                                        '081.jpg',
                                                        '082.jpg',
                                                        '083.jpg',
                                                        '084.jpg',
                                                        '085.jpg',
                                                        '086.jpg',
                                                        '087.jpg',
                                                        '088.jpg',
                                                        '089.jpg',
                                                        '090.jpg',
                                                        '091.jpg',
                                                        '092.jpg',
                                                        '093.jpg',
                                                        '094.jpg',
                                                        '095.jpg',
                                                        '096.jpg',
                                                        '097.jpg',
                                                        '098.jpg',
                                                        '099.jpg',
                                                        '100.jpg',
                                                        '101.jpg',
                                                        '102.jpg',
                                                        '103.jpg',
                                                        '104.jpg',
                                                        '105.jpg',
                                                        '106.jpg',
                                                        '107.jpg',
                                                        '108.jpg',
                                                        '109.jpg',
                                                        '110.jpg',
                                                        '111.jpg',
                                                        '112.jpg',
                                                        '113.jpg',
                                                        '114.jpg',
                                                        '115.jpg',
                                                        '116.jpg',
                                                        '117.jpg',
                                                        '118.jpg',
                                                        '119.jpg',
                                                        '120.jpg',
                                                        '121.jpg',
                                                        '122.jpg',
                                                        '123.jpg',
                                                        '124.jpg',
                                                        '125.jpg',
                                                        '126.jpg',
                                                        '127.jpg',
                                                        '128.jpg',
                                                        '129.jpg',
                                                        '130.jpg',
                                                        '131.jpg',
                                                        '132.jpg',
                                                        '133.jpg',
                                                        '134.jpg',
                                                        '135.jpg',
                                                        '136.jpg',
                                                        '137.jpg',
                                                        '138.jpg',
                                                        '139.jpg',
                                                        '140.jpg')),
        'article_id' => $faker->biasedNumberBetween($min = 1, $max = 200, $function = 'sqrt')
    ];
});

$factory->define(App\Coment::class, function (Faker\Generator $faker){
    return [
        'article_id'    => $faker->biasedNumberBetween($min = 1, $max = 200, $function = 'sqrt'),
        'user_id'       => $faker->biasedNumberBetween($min = 1, $max = 52, $function = 'sqrt'),
        'coment'        => $faker->paragraph($nbSentences = 10, $variableNbSentences = true),
        'created_at'    => $faker->dateTimeBetween($startDate = '0 years', $endDate = 'now'),
        'updated_at'    => $faker->dateTimeBetween($startDate = '0 years', $endDate = 'now')
    ];
});